# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ticker < Formula
  desc "Terminal stock ticker with live updates and position tracking"
  homepage "https://github.com/achannarasappa/ticker"
  version "4.5.10"
  license "GPLv3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/achannarasappa/ticker/releases/download/v4.5.10/ticker-4.5.10-mac-arm64.tar.gz"
      sha256 "2cf93db894e9c2cafd285a20dee15d168b8dd85863db0d2efa1af05db625b0cf"

      def install
        bin.install "ticker"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/achannarasappa/ticker/releases/download/v4.5.10/ticker-4.5.10-mac-amd64.tar.gz"
      sha256 "7bf0448ae22252e4109142c82f6ca8e02ec141bacdb6e7eb882a06e19b653ca0"

      def install
        bin.install "ticker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/achannarasappa/ticker/releases/download/v4.5.10/ticker-4.5.10-linux-amd64.tar.gz"
      sha256 "1581c39e1c3a7a938a1c08e4007a8826becab84e2dc0f4304e10124f5b971b6b"

      def install
        bin.install "ticker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/achannarasappa/ticker/releases/download/v4.5.10/ticker-4.5.10-linux-arm64.tar.gz"
      sha256 "0e7d13ed8910bbc474b6558d7a46f9f8290afd7c28cc7111ceb309505b4b6791"

      def install
        bin.install "ticker"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/achannarasappa/ticker/releases/download/v4.5.10/ticker-4.5.10-linux-armv6.tar.gz"
      sha256 "21414e345c3217096b66fdca186a622405db3d7b58a33ee30fa2128938e912f7"

      def install
        bin.install "ticker"
      end
    end
  end
end
