# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ticker < Formula
  desc "Terminal stock ticker with live updates and position tracking"
  homepage "https://github.com/achannarasappa/ticker"
  version "0.2.2"
  license "GPLv3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/achannarasappa/ticker/releases/download/v0.2.2/ticker-0.2.2-mac-amd64.tar.gz"
    sha256 "6d2bb224a9a8db9b3aaba5cf16126e8ca2a4c713c5902b2e2ab724109f44835b"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/achannarasappa/ticker/releases/download/v0.2.2/ticker-0.2.2-linux-amd64.tar.gz"
    sha256 "795ab704f55613147190fb9b64ad78f381de7344212c4dce81333a757402134b"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/achannarasappa/ticker/releases/download/v0.2.2/ticker-0.2.2-linux-arm64.tar.gz"
    sha256 "67227d74738faab488ec598d78071775ab0ac0214831a01c8436a70279b74bf9"
  end

  def install
    bin.install "ticker"
  end
end
